[project]
name = "pipeline1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "polars>=1.21.0",
    "web3>=7.7.0",
]
